# AWEXOME LABS
# DoesFacebook Configuration File
#
# The appropriate application configuration will be loaded for each
# request based on the callback path of your application. The host
# of each incoming request will be compared against the callback_url
# or ssl_callback_url fields of your app.
#
# Top-level keys in this file are configuration names. If you have one
# app for each environment, however, naming an app after the corresponding
# Rails environment ("development","production",etc.) will provide a
# fallback should the request host not directly resolve to a callback_url
#

name_of_app:
  app_id: 489815807777705
  secret_key: 82e850fde7ac14a81c6ab2c64ffee153
  namespace: embzlntest 
  callback_url: http://radiant-island-4482.herokuapp.com/tabs/
  
name_of_another_app:
  app_id: 489815807777705
  secret_key: 82e850fde7ac14a81c6ab2c64ffee153
  namespace: embzlntest
  callback_url: http://radiant-island-4482.herokuapp.com/tabs/
  
name_of_production_app:
  app_id: 489815807777705
  secret_key: 82e850fde7ac14a81c6ab2c64ffee153
  namespace: embzlntest
  callback_url: http://radiant-island-4482.herokuapp.com/tabs/
  ssl_callback_url: https://radiant-island-4482.herokuapp.com/tabs/
